# baseURL
@baseURL = http://localhost:8000

###
# Find All Users
GET {{ baseURL }}/api/users

###
# Find User By Id
GET {{ baseURL }}/api/users/1

###
# Create User
POST {{ baseURL }}/api/users
Content-Type: application/json

{
    "name": "name 5",
	"description": "description 5"
}

###
# Modify User By Id
PUT {{ baseURL }}/api/users/2
Content-Type: application/json

{
    "name": "name two",
	"description": "description two"
}

###
# Delete User By Id
DELETE {{ baseURL }}api/users/1